Repository slsdetectorgroup/aare, pull requests merged in 2025-05, with the labels that each got.

#168 Added scurve fitting
  include/aare/Fit.hpp
  python/aare/__init__.py
  python/aare/func.py
  python/src/fit.hpp
  src/Fit.cpp
Labels: feature

#175 automated versioning
  CMakeLists.txt
  VERSION
  conda-recipe/meta.yaml
  pyproject.toml
  update_version.py
Labels: enhancement

#176 linking to threads and removed extra ;
  CMakeLists.txt
  src/JungfrauDataFile.cpp
  src/NumpyFile.cpp
  src/RawFile.cpp
  src/RawMasterFile.cpp
Labels: bug

#177 removed extra const on return type, added cast
  include/aare/ClusterVector.hpp
  include/aare/Interpolator.hpp
  src/Fit.cpp
Labels: refactor

#173 RawSubFile support multi file access
  CMakeLists.txt
  include/aare/RawFile.hpp
  include/aare/RawMasterFile.hpp
  include/aare/RawSubFile.hpp
  include/aare/algorithm.hpp
  include/aare/defs.hpp
  include/aare/logger.hpp
  python/examples/play.py
  python/src/raw_file.hpp
  python/tests/test_RawSubFile.py
  src/RawFile.cpp
  src/RawFile.test.cpp
  src/RawMasterFile.cpp
  src/RawSubFile.cpp
  src/RawSubFile.test.cpp
  src/algorithm.test.cpp
Labels: bug
