Repository slsdetectorgroup/aare, pull requests merged in 2025-04, with the labels that each got.

#152 Adding support for Jungfrau .dat files
  CMakeLists.txt
  docs/src/JungfrauDataFile.rst
  docs/src/Tests.rst
  docs/src/algorithm.rst
  docs/src/index.rst
  docs/src/pyJungfrauDataFile.rst
  include/aare/FilePtr.hpp
  include/aare/JungfrauDataFile.hpp
  include/aare/algorithm.hpp
  pyproject.toml
  python/aare/__init__.py
  python/src/jungfrau_data_file.hpp
  python/src/module.cpp
  python/tests/conftest.py
  python/tests/test_jungfrau_dat_files.py
  src/ClusterFile.test.cpp
  src/File.cpp
  src/FilePtr.cpp
  src/JungfrauDataFile.cpp
  src/JungfrauDataFile.test.cpp
  src/algorithm.test.cpp
Labels: enhancement

#163 Custom base for decoding ADC data
  CMakeLists.txt
  include/aare/NDView.hpp
  include/aare/decode.hpp
  python/aare/__init__.py
  python/src/ctb_raw_file.hpp
  src/NDView.test.cpp
  src/decode.cpp
  src/decode.test.cpp
Labels: feature

#147 Api cluster vector
  CMakeLists.txt
  benchmarks/CMakeLists.txt
  benchmarks/calculateeta_benchmark.cpp
  include/aare/CalculateEta.hpp
  include/aare/Cluster.hpp
  include/aare/ClusterCollector.hpp
  include/aare/ClusterFile.hpp
  include/aare/ClusterFileSink.hpp
  include/aare/ClusterFileV2.hpp
  include/aare/ClusterFinder.hpp
  include/aare/ClusterFinderMT.hpp
  include/aare/ClusterVector.hpp
  include/aare/GainMap.hpp
  include/aare/Interpolator.hpp
  python/CMakeLists.txt
  python/aare/ClusterFinder.py
  python/aare/ClusterVector.py
  python/aare/__init__.py
  python/src/bind_ClusterVector.hpp
  python/src/cluster.hpp
  python/src/cluster_file.hpp
  python/src/interpolation.hpp
  python/src/module.cpp
  python/src/np_helper.hpp
  python/tests/conftest.py
  python/tests/test_Cluster.py
  python/tests/test_ClusterFile.py
  python/tests/test_ClusterVector.py
  src/CalculateEta.test.cpp
  src/Cluster.test.cpp
  src/ClusterFile.cpp
  src/ClusterFile.test.cpp
  src/ClusterFinder.test.cpp
  src/ClusterFinderMT.test.cpp
  src/ClusterVector.test.cpp
  src/Interpolator.cpp
  src/algorithm.test.cpp
Labels: enhancement, API

#167 consistent use of ssize_t instead of int64_t
  include/aare/ArrayExpr.hpp
  include/aare/FilePtr.hpp
  include/aare/Frame.hpp
  include/aare/NDArray.hpp
  include/aare/NDView.hpp
  include/aare/NumpyFile.hpp
  include/aare/Pedestal.hpp
  include/aare/VarClusterFinder.hpp
  include/aare/defs.hpp
  python/src/ctb_raw_file.hpp
  python/src/file.hpp
  python/src/np_helper.hpp
  src/FilePtr.cpp
  src/NDArray.test.cpp
  src/NDView.test.cpp
  src/decode.cpp
Labels: refactor
